"""initial schema

Revision ID: f3ad733ed3cd
Revises: 
Create Date: 2026-09-01 17:02:15.100253
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision = 'f3ad733ed3cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_key', sa.String(length=64), nullable=False),
    sa.Column('project', sa.String(length=255), nullable=False),
    sa.Column('repo', sa.String(length=512), nullable=True),
    sa.Column('base_ref', sa.String(length=255), nullable=False),
    sa.Column('head_ref', sa.String(length=255), nullable=False),
    sa.Column('base_sha', sa.String(length=64), nullable=True),
    sa.Column('head_sha', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('pr_url', sa.String(length=512), nullable=True),
    sa.Column('execute_requested', sa.Boolean(), nullable=False),
    sa.Column('llm_requested', sa.Boolean(), nullable=False),
    sa.Column('backend', sa.String(length=32), nullable=True),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.Column('models_reviewed', sa.Integer(), nullable=False),
    sa.Column('degraded_reason', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_id', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_run', schema=None) as batch_op:
        batch_op.create_index('ix_review_run_claim', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_review_run_project_created', ['project', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_run_run_key'), ['run_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_review_run_status'), ['status'], unique=False)

    op.create_table('finding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('rule_id', sa.String(length=32), nullable=False),
    sa.Column('family', sa.String(length=16), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.Column('consequence', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('evidence_note', sa.Text(), nullable=True),
    sa.Column('sql_after', sa.Text(), nullable=True),
    sa.Column('llm_rationale', sa.Text(), nullable=True),
    sa.Column('suppressed_reason', sa.Text(), nullable=True),
    sa.Column('blast_radius', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('execution_delta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('disposition', sa.String(length=32), nullable=True),
    sa.Column('disposition_note', sa.Text(), nullable=True),
    sa.Column('disposition_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['review_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finding_disposition'), ['disposition'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_family'), ['family'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index('ix_finding_fingerprint_created', ['fingerprint', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_finding_severity'), ['severity'], unique=False)

    op.create_table('grain_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('columns', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('rows_per_key', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['review_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grain_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grain_record_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_grain_record_source'), ['source'], unique=False)

    op.create_table('model_delta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('rows_before', sa.Integer(), nullable=True),
    sa.Column('rows_after', sa.Integer(), nullable=True),
    sa.Column('sum_deltas', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('columns_added', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('columns_removed', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('columns_retyped', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('null_rate_deltas', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('build_error', sa.Text(), nullable=True),
    sa.Column('material', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['review_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_delta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_delta_material'), ['material'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_delta_model_name'), ['model_name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_delta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_delta_model_name'))
        batch_op.drop_index(batch_op.f('ix_model_delta_material'))

    op.drop_table('model_delta')
    with op.batch_alter_table('grain_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grain_record_source'))
        batch_op.drop_index(batch_op.f('ix_grain_record_model_name'))

    op.drop_table('grain_record')
    with op.batch_alter_table('finding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finding_severity'))
        batch_op.drop_index(batch_op.f('ix_finding_rule_id'))
        batch_op.drop_index(batch_op.f('ix_finding_model_name'))
        batch_op.drop_index('ix_finding_fingerprint_created')
        batch_op.drop_index(batch_op.f('ix_finding_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_finding_family'))
        batch_op.drop_index(batch_op.f('ix_finding_disposition'))

    op.drop_table('finding')
    with op.batch_alter_table('review_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_run_status'))
        batch_op.drop_index(batch_op.f('ix_review_run_run_key'))
        batch_op.drop_index('ix_review_run_project_created')
        batch_op.drop_index('ix_review_run_claim')

    op.drop_table('review_run')
    # ### end Alembic commands ###
